### ISSUE TITLE
How can I make keys with convex legends?

### ISSUE THREAD

**Issue by yaizawa2e** [rsheldiii/KeyV2#104]
First of all, thank you for creating great project.  KeyV2 is really exciting project for me.

I'm making a plan to create double-shot keys with 3D-printing and casting.
Following steps are my idea.
   1. print keys for making molds
   2. make molds by silicone from printed keys
   3. print inner shot keys
   4. fill epoxy resin to the mold, then put the inner shot
In this idea, I have to print inner shot keys with convex legends.

I tried to set negative $inset_legend_value (e.g. -1.0), but legends went away.

**Comment by rachael7** [comment]
This sounds really exciting. I was hoping to do something very similar. Please keep us updated on your progress!

**Comment by mrebersv** [comment]
So you are looking for the legends to sit proud of the dish, but also have the curve of the dish?  Is that correct?

**Comment by yaizawa2e** [comment]
@mrebersv Yes.  I am a OpenSCAD beginner, so I couldn't understand code of KeyV2.  Now I tried to read and I understand why I can't get embossed legends.
So I made a key model with embossed legends manually.

  1. make legends object by linear_extrude
  2. make plain key model with filled() option
  3. get intersection of 1. and 2.
  4. make plain key model with smaller total_depth parameter, then union with 3.
![image](https://user-images.githubusercontent.com/16421395/126900292-595fc7f4-b902-4bb7-85b2-ec7e67c6d932.png)

And then, I could to start prototyping my double-shot keys.
But I think this method is not easy to port to other projects.

![image](https://user-images.githubusercontent.com/16421395/126900778-faa1c419-99da-4c69-a222-c71651a0e870.png)
![image](https://user-images.githubusercontent.com/16421395/126900841-f663fcaf-f9ef-45c2-bfea-894c2b805385.png)
![image](https://user-images.githubusercontent.com/16421395/126900804-79486fcd-f053-4f43-a673-65f88e634402.png)
![image](https://user-images.githubusercontent.com/16421395/126901020-b66d4a18-b484-43f6-90d9-4a6a4cd5cc53.png)

**Comment by rsheldiii** [comment]
It looks like you solved this, that's a really awesome process!

you can render outset legends on master by setting `$outset_legends` to `true`. In order to get the effect you want, you could then:

1. create whatever keycap you want to have inset legends, looks like you were using `dsa_row(3) key()`
2. create a second keycap with outset legends
3. subract 1mm from `$bottom_key_width`, `$bottom_key_height`, and `$total_depth`
4. intersect the two keycaps to cut the legends off at the correct height

code:

```
intersection() {
  dsa_row(3) key();
  // there is a bug in some openscad versions where you can't re-set a special variable in the scope below
  dsa_row(3) legend("q") union() {
    $total_depth= $total_depth - 0.5;
    $bottom_key_width = $bottom_key_width - 0.5;
    $bottom_key_height = $bottom_key_height - 0.5;
    $outset_legends = true;
    key();
  }
}
```

before intersection it looks like this:
![image](https://user-images.githubusercontent.com/510867/127031671-b49d29a4-7067-4102-ac3f-5cc849af30ed.png)

and after intersection the inner part looks like this:

![image](https://user-images.githubusercontent.com/510867/127031840-f5150f78-f981-4faf-b631-08fb5501dd41.png)

On master right now, you can't set the outset legend height; it is always `$dish_depth`. You could change that by replacing `0` with `$inset_legend_depth` here: https://github.com/rsheldiii/KeyV2/blob/master/src/key.scad#L388 if you want the outer shell of the keycap to be thicker than the inset legend depth. 

I'm going to make an example file for this. cheers!
