### ISSUE TITLE
$dish_type doesn't work

### ISSUE THREAD

**Issue by EMPRSR** [rsheldiii/KeyV2#118]
**What version of OpenSCAD are you on?**
2021.1

**Describe the bug**
Special Variable $dish_type not functional

**To Reproduce**
1. write $dish_type into keys.scad above the key() function
2. change value of $dish_type ($dish_type = "disable")
3. no effect

**Additional context**
neither in the customiser.scad nor the keys.scad file, the special variable $dish_type has any effect. Furthermore the only dish related special variable that seems to work is $dish_offset_x

**Comment by rsheldiii** [comment]
because the `*_row` module (`dcs_row`, `sa_row`, etc) modify the $dish_type, for some reason you cannot redefine it directly underneath the module. 

This does not work:

```
dcs_row() {
  $dish_type = "disable";
  union(){
    key();
  }
}
```

However, this works fine (in 2.x.x and very much should in 1.x.x):

```
dcs_row() {
  union(){
    $dish_type = "disable";
    key();
  }
}
```

![image](https://user-images.githubusercontent.com/510867/154818918-3c8ace4f-81ca-45e6-890a-5643397c6d4b.png)

I'll close this once I verify it works in 1.x.x.

**Comment by rsheldiii** [comment]
The bug exists in 1.x.x and the workaround does indeed also work. I should really figure out why it works this way...
