### ISSUE TITLE
How to make a keycap shorter (low profile) or taller?

### ISSUE THREAD

**Issue by titogarrido** [rsheldiii/KeyV2#164]
I am trying to change $total_depth = 11.5; but it doesn't decrease/increase, the keycap keeps the same z.

What should I do to decrease it size? I am trying to create a base that will be used on a mold, so it is short, and 1 or 2mm less from the side.

Thanks in advance

**Comment by bear454** [comment]
I'm using `$total_depth = 8.3;` to match an XDA profile keycap, and it worked for me. :shrug:

**Comment by rsheldiii** [comment]
$total_depth increases / decreases the size of a keycap. If you'd like a constant decrease you can subtract a number from the current $total_depth:

```
dsa_row(3) {

  $total_depth = $total_depth - 1;
  key();
}
```

There is a bug in some versions of openSCAD where if the module above your code modifies a special variable you _also_ modify, your changes won't take effect. all `*_row()` functions modify the $total_depth, so that would be an issue. You can upgrade OpenSCAD to a newer version (it doesn't happen for me in 2022-10-11) or you can just do this:

```
dsa_row(3) {
  union() {
    $total_depth = $total_depth - 1;
    key();
  }
}
```

I'm going to close this, feel free to reopen if you need more info!
