### ISSUE TITLE
Special/Command characters not respected in legend declaration

### ISSUE THREAD

**Issue by TLMcNulty** [rsheldiii/KeyV2#186]
I would expect to be able to do `\n` when needed, but it just fills a "character not found" glyph.

```
legend("ALT\nTAB", size=2) key();
```

Scant docs/references in other parts of the net suggest this would be the way to do it. 

![Capture](https://user-images.githubusercontent.com/8993166/228398258-1d61c0ee-b9fb-4d42-a664-fe01800d96fc.PNG)

**Comment by TLMcNulty** [comment]
Alternatively how do I newline?

**Comment by CallmeJohnny** [comment]
I use `position=[X,Y]` to change position of the legends, here's an example of putting text in the bottom left and top right: `legend("Text",position=[-0.65,0.65], size=3) legend("Text",position=[0.65,-0.65], size=3)`. `\` is used for Unicode characters so that's why it gives a missing symbol box as `\n` isn't a valid Unicode character.

**Comment by TLMcNulty** [comment]
You're a top bloke. I didn't know multiple legend declarations could be given. Thanks.
