### ISSUE TITLE
Make a possiblity to generate a "top" apart from the rest

### ISSUE THREAD

**Issue by mnivoliez** [rsheldiii/KeyV2#23]
It kinds of follow the idea of ticket #5 . 
In short, I am thinking of "pudding" keycaps. One strategy could be to generate the base and then a top or "hat" that will be assemble later.

**Comment by rsheldiii** [comment]
this is another one of those things that's simple to do but hard to put into a single helper function. 

if you use this code:

```
intersection() {
  key();
  dished(1);
}
```

you get this: 

![image](https://user-images.githubusercontent.com/510867/74580041-f8a7d680-4f6d-11ea-9847-e51e5bf54019.png)


though, that's abusing the `dished()` function a little bit, but it's not too bad. swapping to `intersection` will give you the bottom of the keycap. the `1` is how deep the top is, make sure you don't go past the top thickness.

If you wanted a straight line for the top, you could do this instead:

```
// replace with "intersection" for bottom
difference() {
  key();
  top_of_key() {
    translate([-total_key_width(),-total_key_height(),-$total_depth - 1]) cube([total_key_width()*2, total_key_height()*2, $total_depth]);
  }
}

```

and you get this:

![image](https://user-images.githubusercontent.com/510867/74579969-0c067200-4f6d-11ea-9e6a-082c2f509d54.png)


I might make some example files for some of this stuff since it isn't immediately apparent that you could do these types of things

**Comment by mnivoliez** [comment]
I'll try to work from that. Typically, for this type of task, one would some "assembly" construction to help putting all pieces together at the end.
I believe your second exemple is the way to go.

....

What you will do for keebs....

**Comment by rsheldiii** [comment]
I've added an example script for this in the examples directory: https://github.com/rsheldiii/KeyV2/blob/master/examples/multimaterial_key_top.scad 

I think that's as first class as this is going to get, so I'm going to close this issue. You can follow the directions in the script and modify it to generate different keycaps.
