### ISSUE TITLE
[question] How to achieve a smooth curve across all keys?

### ISSUE THREAD

**Issue by dylanvidya** [rsheldiii/KeyV2#24]
Hello, I came across this [sculpted keyset](https://www.reddit.com/r/MechanicalKeyboards/comments/e69pfw/a_fully_sculpted_keycap_set/) and was inspired to recreate it using KeyV2

<details>
  <summary>Desired effect </summary>
  
![printed_ergo_keys](https://user-images.githubusercontent.com/60530206/73584896-f3c12e00-4469-11ea-83cd-d3c0b2e18c37.jpg)
</details>

<details>
  <summary>My attempt</summary>
  
```
module render_key(info) {
    
    pos = info[0] - [4, 2.5];
    
    x = pos[0];
    y = pos[1];
    
    x2 = pow((x + 2) * 0.75, 2);
    y2 = pow((y + 0) * 1.75, 2);
    y3 = pow((y + 0) * 1.20, 3);
    
    tilt = y3;
    depth = min(max(7, x2 + y2), 12);
    
    $top_skew = 0;
    $dish_depth = 1.2;
    $dish_type = "spherical";
    $dish_skew_y = 0;
    
    $top_tilt = tilt;
    $total_depth = depth;
    
    cherry() key();
}
```
</details>

<details>
  <summary>Results</summary>
  
![render](https://user-images.githubusercontent.com/60530206/73584992-b3ae7b00-446a-11ea-908c-011823308c23.png)

![image](https://user-images.githubusercontent.com/60530206/73585121-0472a380-446c-11ea-85fd-ed37c317e67f.png)

![image](https://user-images.githubusercontent.com/60530206/73585191-c924a480-446c-11ea-82a2-a448c0dbcdb5.png)

</details>

I hope these screenshots do justice in showing how choppy my results are

Is there a recommended or built-in way to achieve the desired effect?

**Comment by rsheldiii** [comment]
sorry for the late response! double-sculpted keycaps being spherically conformed is default behavior now, accessed through the row_profile commands like `dcs_row()`, `sa_row()` etc. It will use the `top_tilt_y` and `total_depth` variables in order to make the intended effect. the first argument to those profile functions is the row and the second is the column; a column value of 0 is a normal keycap, a positive column value tilts to the left and a negative column value tilts to the right.

You can use this to create different fully-sculpted profiles. An easy way to demo that is through the layouts feature, which is still in beta. Doing this:

```
planck_default("hipro", column_sculpt_profile="cresting_wave") key();
```

with `$double_sculpt_radius = 125` will get you this:

![image](https://user-images.githubusercontent.com/510867/74581738-cfdd0c80-4f80-11ea-80c9-b38018f04071.png)

which is pretty close.

you could design a layout file for the board you are working on, or you could just copy the sculpting function I use instead:

```
function cresting_wave(index, total, mod=4) = (index < total/2) ? (((index + 0.5) / total)*mod) : -(mod - ((index + 0.5) / total * mod));
```

the inputs are whatever column you are on and the max number of columns (mod being a way to make the tilt more aggressive). 

let me know if you need any more info!

**Comment by rsheldiii** [comment]
gonna close this for now, though I might add an example in the examples directory

**Comment by hasufell** [comment]
I tried this

```
$double_sculpted = 1;
$double_sculpt_radius = 125;
sa_row(3, 5) 1u() key();
```

And got this:

![Screenshot_2021-05-14_12-38-23](https://user-images.githubusercontent.com/1241845/118259339-539de580-b4b1-11eb-8ad0-111d79cea149.png)
