### ISSUE TITLE
What is the license of this library?

### ISSUE THREAD

**Issue by matoushybl** [rsheldiii/KeyV2#25]
Hi,
what is the license of this library, package.json mentions GPL-V3, but there are no other mentions.

Thanks!

**Comment by rsheldiii** [comment]
I believe I wanted this library under GPLV3, though what that means for an uncompiled language that generates other files is difficult to determine.

My intentions were that:

1. if you redistribute the software or a modified version of the software you need to provide attribution and distribute under the GPL V3
2. if you use the software to generate 3d models, you can sell them or prints of them, and you are not required to provide attribution or changelogs etc since you are not redistributing the software. 
3. there is no warranty and I'm not liable for any damages

I'll add the license to this repository this weekend, thanks for pointing that out!

**Comment by rsheldiii** [comment]
added!
