### ISSUE TITLE
Keyboard health concerns

### ISSUE THREAD

**Issue by MRAAGH** [rsheldiii/KeyV2#34]
This is a *really awesome* generator! However, I am questioning whether 3d printing keycaps is a good idea. According to [this](http://www.center4research.org/bacteria-computer-keyboards-toilet-seats/) and [this](https://all3dp.com/1/food-safe-3d-printing-abs-pla-food-safe-filament/), keyboards and 3d printed parts both have a huge bacteria problem. Printed keycaps put both those problems together!

I think this should be mentioned in the readme.

Any ideas on how to lessen the risk? Unlike when printing kitchenware, I don't think food-safe filament is going to help!

**Comment by rsheldiii** [comment]
Let's start from the top!

To address your first link, [toilet seats are actually pretty clean](https://www.thehealthy.com/home/germs-toilet-seat/) if you're going by total germ count. More importantly though, how many germs exist on a surface is much less important than _what_ germs exist there. Fermented hot sauce (for instance) is rife with bacteria, but it's actually safer because of it: Lactobacillus crowd out other nasty germs and extend the shelf-life of the sauce drastically. So, while keyboards do have quite a few germs on them, they probably aren't all that bad in the grand scheme of things.

Your second link includes one of the best things you can do to make 3d prints food-safe: cover them in a food-safe coating. The brand I use is [Art resin](https://www.artresin.com/blogs/artresin/artresin-passes-food-safety-tests), though I'm sure there are others. It is safe to touch 3d printed objects that are not sealed with food-safe resin though, so handling of 3d printed keycaps shouldn't be any more dangerous than handling any 3d-printed part. Good advice in any scenario is to always wash your hands before eating!

On the topic of food safety, food-safe filament wouldn't help keycaps for the same reason it doesn't help in the kitchen: the material itself will be safe, but the 3d printer's manufacturing process produces many small holes that are almost impossible to clean and serve as shelter for bacteria. In addition most 3d printers are also not certified as food-safe, and some extruder nozzles have trace amounts of lead in them. You shouldn't use any 3d printed plastic in a way that requires food safety long term, in my opinion.

Given that food safety issues are endemic to FDM manufacturing, and keyboards are not a concerning amount dirtier than your average everyday object, I don't think there's a need for a specific call out in the readme, but I'd be happy to discuss further!

**Comment by MRAAGH** [comment]
Oh, sorry! I didn't mean to start a long discussion that'll take your time and keep you from programming, modeling and other important things in your life. My speculation was based on the assumption that if keyboards are one of the biggest bacteria hangouts we come in contact with, it automatically makes them a problem. But maybe ... it just doesn't. Like, if I wash my hands before eating and treat wounds I get on fingers, there's really nothing they can do to me!

Oh, and resin coating is also a cool idea! As long as it doesn't create so much friction that the keyboard becomes difficult to type on

**Comment by rsheldiii** [comment]
no worries! we'll close this for now but we can reopen it if any new information crops up. Cheers!
