### ISSUE TITLE
SA ISO Enter Key possible to print

### ISSUE THREAD

**Issue by JoeGandy** [rsheldiii/KeyV2#48]
Hey apologies for ignorance!

Trying to figure out how to print he ISO Enter Key with the SA profile, is this possible? I saw the open issue on it?

**Comment by rsheldiii** [comment]
hey there! it's possible but very limited and DIY right now. Because the ISO enter shape is concave we can't use `convex_hull` so you have to use either `$linear_extrude_shape = true` or `$skin_extrude_shape = true`. Linear extrude doesn't support tilting, so no row sculpting, and skin extrusion doesn't support rounded corners, and doesn't render in preview mode. Also it looks like you'll have to fiddle with the `$dish_overdraw_width` a bit.

`skin_extrude_shape` is definitely the way forward, I just suck at math and haven't figured out how to get the points to be rounded yet.

**Comment by JoeGandy** [comment]
Awesome that makes sense, thanks for taking the time to answer! Without the sculpting is fine.

I'll have a play around with it, also found a thingiverse model for a iso enter key as backup :) https://www.thingiverse.com/thing:4313733

Thanks very much!
