### ISSUE TITLE
Create a separate STL of just the text, for a double-shot color effect?

### ISSUE THREAD

**Issue by jbcpollak** [rsheldiii/KeyV2#5]
I was just wondering if it would be possible to generate a "positive" version of the inset text labels, in the exact same location as they negative/inset versions are. If that was possible, I think it would allow an FDM printer to create a two-color "double shot" effect keycap.

**Comment by rsheldiii** [comment]
I've looked into supporting this more natively in the past (some kind of `without_key` helper) but this is pretty easy to do with the `difference` command:

```
  dcs_row(3) u(1) {
    difference(){
      legend("q") key();
      key();  
    }
  }
```

![image](https://user-images.githubusercontent.com/510867/66708709-f06f2e80-ed22-11e9-8dd5-96ef85bcdb63.png)

I would suggest using this approach for now until I can figure out a good way to do it that won't grind openSCAD to a halt

**Comment by quasipedia** [comment]
Not sure if this should be a comment to this issue or a new one entirely, but in general it would be interesting to support multi material by being able to generate the inlays that match the insets as a separate group of meshes. :)

**Comment by rsheldiii** [comment]
good idea! That's another thing that can definitely be done right now but isn't really... first class, so to speak. In `key.scad`, legends are added to the keycap via the `legends()` function, and you can ensure things stay under the dish with the `dished()` function, so combining them you can generate what you need for multi-material printing.

with this:

```
legends = ["F1", "1", "q", "a", "z", ""];
for (x = [0:1:4]) {
  translate_u(0,-x) legend(legends[x]) dcs_row(x, 0) {
    key(true);
    dished() {
      legends($inset_legend_depth);
    }
  }
}
```

you can comment out `key(true);` to get just the legends, or vice versa to get the keys themselves. 

You can't really see the legends in the keycaps even if you render them a different color, so here's what the legends look like by themselves: 

![image](https://user-images.githubusercontent.com/510867/72131647-e1f8d900-334a-11ea-8479-d6e78773d933.png)


worth noting that without dishing they may come out pretty nice as-is:

```
legends = ["F1", "1", "q", "a", "z", ""];
for (x = [0:1:4]) {
  translate_u(0,-x) legend(legends[x]) dcs_row(x, 0) {
    key(true);
    legends($inset_legend_depth);
  }
}
```

![image](https://user-images.githubusercontent.com/510867/72131732-1b314900-334b-11ea-8dbe-7a71b0743cac.png)


I'll try to think if there's a better way to implement that, but it works pretty good for now!

**Comment by rsheldiii** [comment]
might be worth having a "tips and tricks" section of the readme or wiki for these kinds of things

**Comment by quasipedia** [comment]
That's pretty awesome!  If I have time I'll try this out this week-end on a couple of test keys! :)

**Comment by rsheldiii** [comment]
I wanted to try using the powder coated prusa bed as a keytop texture and I figured I'd go for broke and give this a spin as well: 

![image](https://user-images.githubusercontent.com/510867/72197666-e0362080-33f1-11ea-914a-65a2127b1334.png)

I don't have multimaterial printing, but you don't need it if your secondary color is just on the first layer, so I printed the caps upside down starting with 0.2mm letters on G20 keycaps since they already have a flat top. I'm getting a little bowing from the heat required to keep the caps seated on the bed but otherwise it came out fantastic, I'm very impressed!

**Comment by rsheldiii** [comment]
This is now in the tips and tricks section: https://github.com/rsheldiii/KeyV2/blob/master/TIPS_AND_TRICKS.md#doubleshot-letters-with-a-regular-printer

and I may also add an example in the examples directory, so I think this is good to close. Thanks everyone!

**Comment by Pitta** [comment]
Man - this would be awesome if it could export the cap & legend inlayed like this for MMU capable machines.

**Comment by rsheldiii** [comment]
@Pitta I just added an example script in the repo for this: https://github.com/rsheldiii/KeyV2/blob/master/examples/multimaterial_legend.scad is that what you're talking about, or is there something else it should be doing?

**Comment by Pitta** [comment]
Oh wow! I tried doing this but wasn't sure how to approach it. OpenSCAD is interesting!

I'll check this out today and let you know! If this lets me do PBT Doubleshot-style caps I think I'm going to be in haven. MMU with PETG, using clear for legends may keep me from spending tons of cash on keycaps!

**Comment by Pitta** [comment]
![image](https://user-images.githubusercontent.com/5016471/80843313-d579e400-8bb8-11ea-98c4-c9a39a49459b.png)

This looks very promising! I'll attempt a print of these in PLA tonight and report back.

**Comment by Pitta** [comment]
![IMG_20200502_113518](https://user-images.githubusercontent.com/5016471/80872847-70ca9200-8c69-11ea-8351-8a56d7dc343f.jpg)
It worked! I may even swap on the smaller nozzle for higher detail.
Thank you!

**Comment by HobbinHood** [comment]
Figured it'd be wrong to create a new issue for a related question regarding the `$inset_legend_depth`:
The default is set to 0.2 and I set my slicer software to a layer height of 0.2, too. But in the slicing preview it shows as three layers. I'm confused. /o\

**Comment by Pitta** [comment]
Curious - can this work with artisan style stl imports? Been fussing with this but can't seem to layer in an STL and get it to render out separately like this did with legends.

**Comment by rsheldiii** [comment]
that's one of those "unsupported supported" workflows. You can do this:

```
difference() {
  key() {
    cube(10);
  }
  key();
}
```

Or preferably this:

```
difference() {
  top_of_key() {
    cube(10);
  }
  key();
}
```
 
since the first one doesn't work in preview mode. ![Output, for reference.](https://user-images.githubusercontent.com/510867/83719004-2d669900-a604-11ea-9e2f-f9c0a8eac8b9.png). I'm in a weird state on master right now so it should work the same, but if the second one doesn't work the first one should always work.

**Comment by Pitta** [comment]
I'll play with it tomorrow!
Your patience and willingness to help out here is very much appreciated. This project is so cool. I wish I knew this appreciation better.

**Comment by Pitta** [comment]
I never did get that figured out... Would still like to.

I'm also interested in front legends as well. Ideally simultaneously so I can have my keys show whats on the layer underneath, like arrows on the front of HJKL, for example. In a multi material print, this would look amazing.

**Comment by rsheldiii** [comment]
Can you show me your code for the artisan?

front-facing legends should work with the existing dual legends code. if you were to replace the contents of `examples/multimaterial_legend.scad` with this:


```
include <../includes.scad>

/* in this example we'll use some openSCAD to generate files for printing inset
   legends with a multimaterial printer.
*/

legends = ["F1", "1", "q", "a", "z", ""];
front_facing_legends = ["n", "e", "a", "t", "0"];
for (x = [0:1:4]) {
  translate_u(0,-x) legend(legends[x]) front_legend(front_facing_legends[x]) dcs_row(x, 0) {
    // swap the debug()s to render opposite part
    debug() key(true);
    /* debug() */ dished() {
      legends($inset_legend_depth);
      front_legends($inset_legend_depth);
    }
  }
}

```

you should get something like this:

![image](https://user-images.githubusercontent.com/510867/84935887-65abb400-b0a7-11ea-87b9-98a1a293ad72.png)


the legends will stick out a bit, unlike the legends on the top surface, because there's nothing to clip them off. But since they're not on the top I don't think that's a huge issue.

**Comment by HobbinHood** [comment]
Just curious about another thing, regarding the issue I just commented on over at Slic3r:
The problem with the 2nd layer only occurs, if I set `dish_type` to `disable`. If I use `flat`, no weird layer merging occurs, but the printing won't work with a 3 to 5 layer high prior printed legend.
Did this ever happen to someone?

**Comment by Pitta** [comment]
So, dual legend printing works! (Please ignore the cosmetic defects and color choices on this key - this is just testing)

It seems like there is no variable to tweak to get the front legends to print flush, as you mentioned. I tried sanding this one flat and will have to decide if I'm going to do that for all of them. I want to print some in the profile and color I intend to use long term and see how those look and feel.

-------------

As for the artisan legend being flush cut... I dont have any code because I simply never landed close to something useable. The idea is I have some logos in SVG I could extrude to 3d to be like 1mm thick, then use the artisan cap option to pull in the stl. It would be neat to be able to have those flush cut like the top legends, and exported independently to get that double shot look. That or I need to find out how to make fonts and turn the logos into a font and do it that way.

**Comment by jbcpollak** [comment]
I think the image didn't get attached?

**Comment by Pitta** [comment]
Fixed!
