### ISSUE TITLE
Key Length

### ISSUE THREAD

**Issue by lohmobius** [rsheldiii/KeyV2#50]
Unable to input any key length as decimal (3.5 or 6.25).  Using OpenSCAD Customizer.

**Comment by rsheldiii** [comment]
works for me on master:

```
dcs_row(5) legend("⇪", size=9) {
  $key_length = 2.25;
  key();
}


translate_u(0,1) dcs_row(5) legend("⇪", size=9) {
  $key_length = 2;
  key();
}
```

gives:

![image](https://user-images.githubusercontent.com/510867/84936414-2e89d280-b0a8-11ea-9e9e-c93d82e53c6f.png)


you can also use the `u()` function instead of changing `$key_length` directly.

Depending on your code, you might be experiencing a bug in OpenSCAD. Special variable changes don't happen if the variable was changed in the calling function (I believe). For instance, `stepped_caps_lock` looks like this:

```
module stepped_caps_lock() {
  u(1.75) {
    $stem_positions = [[-5, 0]];
    children();
  }
}
```

and calling 

```
translate_u(0,1) dcs_row(5) legend("⇪", size=9) stepped_caps_lock() {
  $key_length = 3;
  key();
}
```

results in a key that is 1.75u long, not 3. The solution is to add a no-op `union` in there:

```
translate_u(0,1) dcs_row(5) legend("⇪", size=9) stepped_caps_lock() {
  union() {
    $key_length = 3;
    key();
  }
}
```

^ that code produces the correct output.

Can you double check if using `u` or adding a `union` call around the `$key_length` change and siblings fixes the problem for you?

**Comment by rsheldiii** [comment]
closing as it's been a while. if you need more context or this doesn't solve the problem please reopen
