### ISSUE TITLE
OEM with box or rounded stem causes supports to protrude key

### ISSUE THREAD

**Issue by Forge-Media** [rsheldiii/KeyV2#61]
Hi.

Brand new to your fantastic key design tool. I'm trying to print some custom OEM row 5 (escape) keys for some friends. But I've run into a bit of an issue, probably due to being unfamiliar with OpenSCAD and your library.

I initially printed the OEM key with the default stem, but forgot that I use Kailh Box Jade key for my escape. So I went to alter this to the rounded_cherry stem but desired to include stem supports to help in the printing. (_I'm printing on my own Form2 SLA_). The issue is best described with the image bellow:

![image](https://user-images.githubusercontent.com/7041755/92160828-8a523500-ee27-11ea-9163-feb75f794f0a.png)

As can be seen the "tines" stem supports protrude the outside of the key.  If I change the key profile to dcs this is no longer an issue. But I would like to print both oem and dcs types for friends, depending on their keyboard.

Do you know how I could fix this?

**Comment by schapmangt** [comment]
You will also want to consider that the stem support tines intersect the box of a Kailh Box switch, so you will need to cut the tines after printing for the key to fit on that switch.

**Comment by bliind** [comment]
I know this was over a year ago but this PR fixes this issue: https://github.com/rsheldiii/KeyV2/pull/47

**Comment by rsheldiii** [comment]
fixed in #129. In v2.0.0 I ended up implementing something similar to @bliind's suggestion [here](https://github.com/rsheldiii/KeyV2/blob/master/src/key.scad#L220-L225), which takes the inside of the keycap and differences the inside features (call that inside-plus-features), then takes the outside shape of the keycap and differences the inside-plus-features from that. The result is that nothing defined in inside_features can ever poke out of the keycap, so you can extend stem support / keystems to infinity if you want to
