### ISSUE TITLE
cherry_cross has vertical and horizontal dimensions reversed

### ISSUE THREAD

**Issue by kibogaoka** [rsheldiii/KeyV2#7]
Maybe I'm misunderstanding how this function works, but it appears the cherry cross tine thicknesses are reversed. Here is the function in question

```scad
// .005 purely for aesthetics, to get rid of that ugly crosshatch
function cherry_cross(slop, extra_vertical = 0) = [
  // horizontal tine
  [4.03 + slop, 1.15 + slop / 3],
  // vertical tine
  [1.25 + slop / 3, 4.23 + extra_vertical + slop / 3 + .005],
];
```

This gives the horizontal tine and vertical tines thicknesses of 1.15 and 1.25, respectively. When measuring gateron switches with calipers, the opposite appears to be the case.

I have printed a full set of keycaps with 0.3 slop, and they have significant side-to-side wobble despite being very tight vertically. When swapping the tine dimensions here, and lowering the slop to 0.24, I'm now getting far better fitment.

Here is the version of the function I'm using to print my keycaps now

```scad
function cherry_cross(slop, extra_vertical = 0) = [
  // horizontal tine
  [4.03 + slop, 1.25 + slop],
  // vertical tine
  [1.15 + slop, 4.23 + extra_vertical + slop],
];
```

(I removed the divide-by-three for my personal implementation just so the entered slop value would correspond to the exact amount of clearance)

**Comment by rsheldiii** [comment]
Hey there! sorry for the late response, I must have missed the email.

Looking at the numbers now you're definitely right, the vertical tine is smaller on all the switches I have. I had a much worse printer back when I wrote that, so odds are I didn't notice due to elephant's foot / bad dimensional accuracy.

I'll rattle off a few test prints and integrate these changes soon. thanks for finding this!

**Comment by kibogaoka** [comment]
No problem man, and thanks for the awesome library.
