### ISSUE TITLE
Question - stepped caps / iso enter

### ISSUE THREAD

**Issue by paulgali** [rsheldiii/KeyV2#70]
`dcs_row(3) stepped_caps_lock() key();`

I can see what you are doing, but, why cant the right side of the cap sink, so it actually models as stepped?

![image](https://user-images.githubusercontent.com/23615789/98092030-a31aad80-1e9f-11eb-92e9-4bfa7bc0ed54.png)
![image](https://user-images.githubusercontent.com/23615789/98092052-a9108e80-1e9f-11eb-9267-103fde0556a0.png)

A similar story for ISO enter. I've read through the docs, and there's a strange issue around the 'elbow'. Notice also by running the following, you see the bottom stab clipping. Ideally if its just calling the module, can we just update that code? I was a bit lost on the elbow explanation however.

`dcs_row(2) iso_enter() key();`

![image](https://user-images.githubusercontent.com/23615789/98092240-df4e0e00-1e9f-11eb-9ad8-5757c10f7d14.png)

Thank you for this work so far! I have forked it for some custom keysizes (think calling spacebar1() or spacebar7() etc). Will make a public DCS model template available once I get everything together. You did amazing work!

**Comment by rsheldiii** [comment]
Stepped caps lock and ISO enter have always been pain points. The good news is ISO enter is _finally_ supported, if you use the latest code. The bad news is stepped caps lock isn't any closer than before.

The only thing I can think to do with stepped caps lock is maybe to render a half-height keycap, then place a little cap on top that becomes the taller portion of the keycap, instead of trying to support it first-part. The top bit will be 100% filled with plastic, but it would otherwise achieve the effect.

I'm going to close this, but I've made note of adding stepped caps lock here: https://github.com/rsheldiii/KeyV2/issues/136
