### ISSUE TITLE
Support for ANSI keyboard layout

### ISSUE THREAD

**Issue by donicrosby** [rsheldiii/KeyV2#77]
I was wondering if there is a way to generate the standard ANSI 104 key layout with your library, does the generator support 1Ux2U Keys in the vertical orientation?

**Comment by rsheldiii** [comment]
Hello,
 There is support for an ISO enter key now. I don't have a layout file yet, nor can I really guarantee the ISO enter fits since I don't have an ISO keyboard, but it does work!
 
 Closing this, going to make an enhancement request for an ISO layout: https://github.com/rsheldiii/KeyV2/issues/137
