### ISSUE TITLE
Stem by itself – no keycap?

### ISSUE THREAD

**Issue by jacobpatton** [rsheldiii/KeyV2#82]
How would I go about generating a stem by itself (to glue into an artisan keycap)? I've tried setting top & wall thickness to 0 with no luck…

**Comment by AaronVerDow** [comment]
Figured this out while writing https://github.com/rsheldiii/KeyV2/pull/90/files

```
include <./includes.scad>;

stem($stem_type, $stem_throw, $stem_slop, $stem_throw);
```

**Comment by rsheldiii** [comment]
This is still the best way to render stems. Stems and anything else that goes inside the key shape are now rendered as a negative, that is differenced from the total outer shape of the keycap, so it's a little difficult to derive their exact shape now. Using `$stem_throw` instead of `stem_height()` (which will come out wrong) is a good idea.
